apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:gmb3hOtHRxnzNcL++BIeYMo=,iv:duRySCFAITd5MJcyDD7syqg7H4dsPqri3MFvBR68MvU=,tag:PykKX0vsAPnwk70Bygv0tA==,type:str]
    client_secret: ENC[AES256_GCM,data:s1rbfcwindtakXmjwo+OereysNMypzjdXkkWm5bd37PlMCB3iuOV/6FeDVNO629PXe9wqnudrwS8O8eeRichFw==,iv:zWo/WdiSMXke4tBgG50h01rMbalbDzWzhfnWcWlo5Dk=,tag:qf4vOgEY1UbCMgHRc7EeXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEFZUW1YVkJIMHYxTm0x
            cUZRcWJuZzR5ajVuYzVvU3p6VGxmWTVwNEhRClVsbnF3WVhVU29PRk5YS1FWZnN1
            cTZYWXFuTlVCNjdYUThaVEZSWkdpRjAKLS0tIFZsa2xNWFBjN1p6dlJ4QXptL0dq
            UWhXVjZYYlZlOTluM3duUDF1c3hQbXcKuvKQCJd7C+XCCtSj6B5Z20dqsPX7S/+l
            U/dM0lKW5j55G4aaOjR579uMygQteVGfujkZPe6D25HxYOsbCJyFSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykets7lkfveyjaypuyaxec6ps54686n2afz8t53x7p5x2fayrakqy7kcap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T10:57:15Z"
    mac: ENC[AES256_GCM,data:fWgk0vINYXo1V7lgq+tYqyHt7l2WJv5TlTKZXyUmInKutJ88EtaS9JTf2+18KjrbWweM7LbQou55+PE3EgkxnP1ks/bvTowIq3Ofp5XzC8rT2KiJbHEbcb8X2UygjXi6urj8S4tl0T+pDwbJDY6pWk9rdvRLCm3usD6Fm0ebsVE=,iv:oQ3jf0dvLSXPa+tbbip5zziHruNYYZ3suT6X1AnIO2w=,tag:t7vgIpBsqEGPqnKMJQal5Q==,type:str]
    version: 3.13.3
