apiVersion: v1
kind: Secret
metadata:
    name: ntfy-gateway
    namespace: flux-system
stringData:
    FLUX_SECRET: ENC[AES256_GCM,data:CCBxzVEYy7nZLMclW/4r6Dcg1HS5wcKmFQfh0T4UfxKRpcMCqk3tRSc6urw=,iv:Dejto+1i30P/qk4Fp/3+LzI6eW5D6UvFMYgU7LIz6Fg=,tag:RzKwNlOGMrFegbz6P+8AQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUHlyd2x0Skg5SkdXMEpI
            NG9qQzhUYUdDZldRQTFKSGJicW8zTVAvOFZrClhvTW11SDdoUm80MnJ6NzFHS01t
            MCtIa20xdkFzQ2FhQ25vUDAzcEpzZ0EKLS0tIGh5SXQ2YUpZREpkcmpsclc1b1Fi
            Z2NwQ3BHdGpnRE5uWFp6T0E5SUZoeWsKFciXr3RxQvGrgookVGy/8WCjHx4S0ixH
            LBllBfxaBznkzmrex94jhxBFXk+jalQRURd7Sy6qnFU4kWh+MKjP+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykets7lkfveyjaypuyaxec6ps54686n2afz8t53x7p5x2fayrakqy7kcap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T20:32:53Z"
    mac: ENC[AES256_GCM,data:7OqXyYsHD1Iimb0bWNQPhknMljv0ZP/MC6eRWUGV2ofSdy6IMhACkzt2wcLNOxlFKDXLi2FpsAXI+uuV9f44KB82DpwVHPGn5yLlua+2ozNxugCBmeKiKhvrIutph4MP0mUMWRFeUiOdoDwTB2Scy4HddYhqbY5u5vEdx3YEomA=,iv:vlJg7dJ1Rfe8JxNLbisIWxEydVgUo4E8wEurGJZ6jWk=,tag:qBuL6jTYkChDRrQGjA0+ug==,type:str]
    version: 3.13.3
