apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
spec:
  storageClassName: ""
  volumeName: ntfy-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
