---
apiVersion: v1
kind: Secret
metadata:
    name: ntfy-gateway
    namespace: flux-system
stringData:
    headers: ENC[AES256_GCM,data:2jjIxuxzXrUQ5VS9BMB03GcPAKIx02KNtQW5kZkngW0VvmDZNioOhjl/sWR9c5k0iywKKbxEB0fO/hIlkcp5VFBHqw==,iv:GkkgQGH4DUtDGgwZYxUbfbIJ00/BUYV1sTtBKJ9uS/U=,tag:QESlnbNVEirygMZwpzYaAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudGdLWnF3VUY3ODc4UlUx
            ZUNRNUgzRTdheWVJeFNWRTc2ZFdRU1h1UjFNClBoZDIwbkFuTVRQcVMvTUpGc2RY
            SThuUERVUzVrSTVNOGhXQ2Y1MUgwVmsKLS0tIERSdTBsL2JGOHU0MmU4RStIcS8z
            VDdiWVBjcUVDSG8zMXV2YUVvMVRoNEUKu9rbhSQ0UAjJiVYwFvrvM9zTKcXFLAWy
            f+d+TiEp+7jhw2gN4DRqD+5BG7g79EB0jsF4ZdbMPZOhmapEO9ESrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykets7lkfveyjaypuyaxec6ps54686n2afz8t53x7p5x2fayrakqy7kcap
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T20:30:05Z"
    mac: ENC[AES256_GCM,data:mxDcPlfv/i49jX+p7pvOHKVnAOq768ulDoaeVQ2gB1Ho/U0VYWDqNUgGveH/d2mIQ0GqRvOtRbmXTm1kK0KB9WeOBE92pIyzAf+SWD6H1LX/mZJm4ZkxAj6s7MnBbpjaiO5VzWfQCqZcjxPzy1NPUVjQ47vsrD9D4UL5gotNttc=,iv:6cYucMgulVsXsyNdKDFc+V8qMuafo0sTmPZ88loRKOE=,tag:o37LDk0MKae7u1xOkHW1iA==,type:str]
    version: 3.13.3
